on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TARGET_BRANCH: static

jobs:
  build:
    name: Build astro
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Use Node.jobs
        uses: actions/setup-node@main
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Archive static folder
        uses: actions/upload-artifact@main
        with:
          name: static
          path: static

  push:
    name: Push from GitHub Actions
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: static
          path: static
      - name: Setup Git global settings
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global init.defaultBranch "${TARGET_BRANCH}"
      - name: Push GitHub
        run: |
          cd static
          git init
          git add -A
          git commit -m "Build at GitHub Actions"
          git remote add origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git push --force origin ${TARGET_BRANCH}